### ISSUE TITLE
Allow accessing `response()` and `request()` without providing a matcher

### ISSUE THREAD

**Issue by ianwsperber** [FormidableLabs/yesno#19]
Users should be able to access `response()` and `request()` methods for getting a single intercepted request/response without providing a matcher. We could either A: Making the matcher filter optional B: Make request/response available on yesno directly.

I prefer option A, because we will only bloat the API if we continue to add methods from `matching()` onto `yesno` as shortcuts.

For an example, see https://github.com/estrada9166/yesno-easygraphql/blob/master/test/easygraphql-tester.js#L46:

```javascript
const response = yesno.matching(/\//).response()
```

which we would like to change to:

```javascript
const response = yesno.matching().response()
```

**Comment by mscottx88** [comment]
@ianwsperber can the `matching` receive empty parens?

**Comment by mscottx88** [comment]
oh haha i see that is what we're after
