### ISSUE TITLE
Generate API section of README using typedoc or similar tooling

### ISSUE THREAD

**Issue by ianwsperber** [FormidableLabs/yesno#32]
Currently we manually update the API section of the README. We should generate this section using typedoc or similar tool. Unclear what tooling is out there currently. If typedoc doesn't support this out of the box, might be a plugin we could use to add this feature (maybe https://github.com/tgreyuk/typedoc-plugin-markdown?)

**Comment by jacebenson** [comment]
I was looking at this, trying to see if i could help.
I forked the repo and set it up on my fork, appears your have to set up an output directory so it copies the base level readme, appends links to it for it's `external modules`.

I'd suggest looking at my [fork/branch](https://github.com/jacebenson/yesno/tree/typedoc)

You'll notice a new directory called `/docs` and in that is the output of the typedocs output.

**Comment by ianwsperber** [comment]
Hi @jacebenson! Sorry for missing your comment. It seems we have a solution in place for now, but thanks for taking a look!

**Comment by jacebenson** [comment]
No worries.
