### ISSUE TITLE
Support Node 6

### ISSUE THREAD

**Issue by ianwsperber** [FormidableLabs/yesno#7]
- [x] Replace `async`/`await` in API with Promises
- [x] Update `package.json:engines` restriction which currently restricts to node8+

**Comment by ryan-roemer** [comment]
It technically could, but at least for babel, the generated code from `async/await` is just a monstrosity of awful, so really would be better to have native, terse promises. Maybe we look at the TS generated output for that and see first if it's equally as bad?

... as another factor to consider node6 is EOL'ed `April 2019`

**Comment by ryan-roemer** [comment]
One other thing to keep in mind, we **only** need to do this for `src`, not `examples` or `test` (we could just omit testing 6 in CI). Doing a quick search just yielded only a handful of async/await in actual `src`.

Easiest path may just be to swap those out, leave CI as is and be done with it!
